
lang: ruby

rvm:
  - 2.6.3

before_install:
  - gem install bundler
  - gem install jekyll

install:
  - bundle install --path vendor/bundle

script:
  - bundle exec jekyll build -d builded

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: builded
  target_branch: master
  fqdn: lugs.ir
  repo: herotux/lugsir
  on:
branch: master
