# Site Settings
title: لاگز | معرفی گروه های کاربری لینوکس
email: gshs99@gmail.com
description: معرفی گروه های کاربری لینوکس در سطح کشور.
#baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
url: "http://www.lugs.ir" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: freetux
user_description: حمید صیدی ،دوستدار گنو/لینوکس و نرم افزار آزاد.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: herotux
# facebook_username: facebook_username
twitter_username: freetux
instagram_username: freetux
# linkedin_username: linkedin_username
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: خانه
    url: /
  - title: درباره
    url: /about/
  - title: تماس با لاگز
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']


osm-links:
  - title: OpenStreetMap چیست؟
    url: /introduction/
  - title: چطور نقشه کشی رو شروع کنم؟
    url: /beginner/
  - title: شروع‌کار osm
    url: /start-osm/
  - title: داده های openstreetmap
    url: /osm-data/
  - title: کپی - چسباندن
    url: /copy-past/
  - title: JOSM- شروع کار با
    url: /start-josm/
  - title: JOSM- ابزارهای ویرایش با JOSM
    url: /josm-tools/
  - title: فرآیند ویرایش در JOSM
    url: /more-josm/
  - title: نقشه‌کشی انسان‌دوستانه
    url: /humanitarian/
  - title: اصلاح اشکالات مربوط به مسیریابی نقشه osm
    url: /osm-distance/
  - title: نقشه‌کشی با گوشی هوشمند، دستگاه GPS و یا کاغذ
    url: /mobile_mapping/
  - title: رسم نقشه از راه دور
    url: /remote-mapping/
  - title: استفاده از داده‌های OSM در QGIS
    url: /osm-qgis/
  - title: کجا راهنمایی و کمک بیشتری دریافت می‌کنم؟
    url: /moving-forward/
  - title: راهنمای رسم محلات در osm
    url: /draw-neighbourhood/
  - title: ثبت و ریلیشن بندی دوربین کنترل سرعت
    url: /osm-speed-camera/
  - title: تگ های پرکاربرد
    url: /osm-tags/
  - title: آموزش تغییر لایه ها و داده های نقشه در ویرایشگر id
    url: /osm-layers/
  - title: کار با فایل gpx در josm
    url: /josm-gpx